In [1]:
import pandas as pd

from data_processor.ChinaStockDownloader import ChinaStockDownloader

In [2]:
# dl = ChinaStockDownloader("2010-01-01", "2022-07-01", index="TICKER_LIST_590")

# df = dl.download_fundament(remain_statdate=True)

In [3]:
time_table = pd.read_csv("./data/590_fund_time.csv", index_col=0)
time_table.tic = time_table.tic.apply(lambda x: x[3:])
time_table

          tic     pubDate    statDate
0      002287  2010-04-22  2010-03-31
1      002287  2010-08-27  2010-06-30
2      002287  2010-10-26  2010-09-30
3      002287  2011-04-01  2010-12-31
4      002287  2011-04-22  2011-03-31
...       ...         ...         ...
28905  000800  2021-04-30  2021-03-31
28906  000800  2021-08-28  2021-06-30
28907  000800  2021-10-30  2021-09-30
28908  000800  2022-03-31  2021-12-31
28909  000800  2022-04-30  2022-03-31

[28910 rows x 3 columns]

In [4]:
df = time_table.set_index('tic')
df

           pubDate    statDate
tic
002287  2010-04-22  2010-03-31
002287  2010-08-27  2010-06-30
002287  2010-10-26  2010-09-30
002287  2011-04-01  2010-12-31
002287  2011-04-22  2011-03-31
...            ...         ...
000800  2021-04-30  2021-03-31
000800  2021-08-28  2021-06-30
000800  2021-10-30  2021-09-30
000800  2022-03-31  2021-12-31
000800  2022-04-30  2022-03-31

[28910 rows x 2 columns]

In [5]:
fund_path = "./data/fundamental_of_592/"

In [15]:
sample_fund_df = pd.read_csv("./data/fundamental_of_592/000011.csv", index_col=0)
sample_fund_df.columns

Index(['date', 'grossMargin', 'revenue', 'inventory_days', 'receivable_days',
       'payable_days', 'debt_ratio', 'fixedasset', 'freecashflow',
       'cashtoemployee', 'netmargin', 'num_shareholder', 'net_equity'],
      dtype='object')

In [21]:
from pprint import pprint

In [28]:
tic_list = list(time_table.tic.unique())
tic_with_missing = 0
tic_with_complete_missing_col = 0
complete_missing_col = dict(
    zip(sample_fund_df.columns, [0 for i in range(len(sample_fund_df.columns))])
)

for tic in tic_list:
    complete_missing_flag = False
    fund_df = pd.read_csv(fund_path + tic + ".csv", index_col=0).iloc[8:]
    fund_df["tic"] = tic
    pub_d = df.loc[tic]["pubDate"].to_list()
    stat_d = df.loc[tic]["statDate"].to_list()
    trans_dict = dict(zip(stat_d, pub_d))
    fund_df.date = fund_df.date.map(trans_dict)
    if fund_df.isnull().any().any():
        tic_with_missing += 1
        print(f"\n{tic} has missing data in: ")
        for col in fund_df.columns:
            null_num = fund_df.isnull()[col].sum()
            if null_num > 0:
                print(f"{col}: {null_num}")
            if null_num == 48:
                complete_missing_flag = True
                complete_missing_col[col] += 1
        if complete_missing_flag:
            tic_with_complete_missing_col += 1

print(f"\nThere are {tic_with_missing} stocks have missing data")
print(
    f"{tic_with_complete_missing_col} stocks have columns that are missing completely.\n"
)
print(f"The number of complete missing column: ")
for key, value in complete_missing_col.items():
    print(f"{key}: {value}")

000543 has missing data in:
inventory_days: 1

600131 has missing data in:
receivable_days: 5

002245 has missing data in:
receivable_days: 1

600809 has missing data in:
cashtoemployee: 1

601328 has missing data in:
grossMargin: 48
inventory_days: 48
receivable_days: 48
payable_days: 48
fixedasset: 48
freecashflow: 25
netmargin: 48

000898 has missing data in:
receivable_days: 1

600012 has missing data in:
receivable_days: 48

002024 has missing data in:
receivable_days: 1

600188 has missing data in:
receivable_days: 1

600403 has missing data in:
grossMargin: 2
revenue: 2
inventory_days: 3
receivable_days: 2
payable_days: 2
fixedasset: 3

600036 has missing data in:
grossMargin: 48
inventory_days: 48
receivable_days: 48
payable_days: 48
fixedasset: 48
freecashflow: 26
netmargin: 48

601808 has missing data in:
receivable_days: 2

600605 has missing data in:
inventory_days: 15

600287 has missing data in:
payable_days: 1

600887 has missing data in:
receivable_days: 1

600598 has missing data in:
receivable_days: 1

600371 has missing data in:
receivable_days: 18

600548 has missing data in:
receivable_days: 1

600007 has missing data in:
receivable_days: 2

601998 has missing data in:
grossMargin: 48
inventory_days: 48
receivable_days: 48
payable_days: 48
fixedasset: 48
freecashflow: 27
netmargin: 48

000686 has missing data in:
grossMargin: 48
inventory_days: 48
receivable_days: 48
payable_days: 48
fixedasset: 48
freecashflow: 34
netmargin: 48

002038 has missing data in:
receivable_days: 1

000985 has missing data in:
receivable_days: 9

601099 has missing data in:
grossMargin: 48
inventory_days: 48
receivable_days: 48
payable_days: 48
fixedasset: 48
freecashflow: 37
netmargin: 48

002142 has missing data in:
grossMargin: 48
inventory_days: 48
receivable_days: 48
payable_days: 48
fixedasset: 48
freecashflow: 38
netmargin: 48

000783 has missing data in:
grossMargin: 48
inventory_days: 48
receivable_days: 48
payable_days: 48
fixedasset: 48
freecashflow: 37
netmargin: 48

600029 has missing data in:
payable_days: 1
freecashflow: 1

600109 has missing data in:
grossMargin: 48
inventory_days: 48
receivable_days: 48
payable_days: 48
fixedasset: 48
freecashflow: 35
netmargin: 48

000637 has missing data in:
inventory_days: 1

600015 has missing data in:
grossMargin: 48
inventory_days: 48
receivable_days: 48
payable_days: 48
fixedasset: 48
freecashflow: 36
netmargin: 48

600348 has missing data in:
netmargin: 3

601939 has missing data in:
grossMargin: 48
inventory_days: 48
receivable_days: 48
payable_days: 48
fixedasset: 48
freecashflow: 24
netmargin: 48

000060 has missing data in:
debt_ratio: 1

002058 has missing data in:
freecashflow: 1

000430 has missing data in:
receivable_days: 1

600792 has missing data in:
freecashflow: 1

600716 has missing data in:
inventory_days: 1
receivable_days: 28

600999 has missing data in:
grossMargin: 48
inventory_days: 48
receivable_days: 48
payable_days: 48
fixedasset: 48
freecashflow: 30
netmargin: 48

600409 has missing data in:
cashtoemployee: 1

600992 has missing data in:
fixedasset: 1

600033 has missing data in:
receivable_days: 1

600838 has missing data in:
debt_ratio: 1
freecashflow: 1

002307 has missing data in:
receivable_days: 2

600011 has missing data in:
receivable_days: 1

600184 has missing data in:
freecashflow: 1

601988 has missing data in:
grossMargin: 48
inventory_days: 48
receivable_days: 48
payable_days: 48
fixedasset: 48
freecashflow: 26
netmargin: 48

601333 has missing data in:
receivable_days: 2

600027 has missing data in:
receivable_days: 1

002177 has missing data in:
cashtoemployee: 1

000993 has missing data in:
payable_days: 1

002285 has missing data in:
inventory_days: 30

600573 has missing data in:
receivable_days: 15

000728 has missing data in:
grossMargin: 48
inventory_days: 48
receivable_days: 48
payable_days: 48
fixedasset: 48
freecashflow: 33
netmargin: 48

600684 has missing data in:
receivable_days: 11

600805 has missing data in:
receivable_days: 1

002073 has missing data in:
cashtoemployee: 1

600350 has missing data in:
cashtoemployee: 1

000776 has missing data in:
grossMargin: 48
inventory_days: 48
receivable_days: 48
payable_days: 48
fixedasset: 48
freecashflow: 30
netmargin: 47

601111 has missing data in:
receivable_days: 2
payable_days: 1
freecashflow: 1

000702 has missing data in:
receivable_days: 1

601857 has missing data in:
receivable_days: 2
payable_days: 1

002208 has missing data in:
receivable_days: 31

601398 has missing data in:
grossMargin: 48
inventory_days: 48
receivable_days: 48
payable_days: 48
fixedasset: 48
freecashflow: 24
netmargin: 48

000554 has missing data in:
receivable_days: 1

600030 has missing data in:
grossMargin: 48
inventory_days: 48
receivable_days: 48
payable_days: 48
fixedasset: 48
freecashflow: 27
netmargin: 48

002275 has missing data in:
receivable_days: 1

000525 has missing data in:
receivable_days: 1
payable_days: 1

000021 has missing data in:
receivable_days: 2

600837 has missing data in:
grossMargin: 48
inventory_days: 48
receivable_days: 48
payable_days: 48
fixedasset: 48
freecashflow: 28
netmargin: 48

601169 has missing data in:
grossMargin: 48
inventory_days: 48
receivable_days: 48
payable_days: 48
fixedasset: 48
freecashflow: 39
netmargin: 48

000880 has missing data in:
freecashflow: 1

000402 has missing data in:
receivable_days: 1

601788 has missing data in:
grossMargin: 48
inventory_days: 48
receivable_days: 48
payable_days: 48
fixedasset: 48
freecashflow: 28
netmargin: 48

000039 has missing data in:
receivable_days: 2

600697 has missing data in:
receivable_days: 1

600230 has missing data in:
receivable_days: 3

601117 has missing data in:
inventory_days: 1

601009 has missing data in:
grossMargin: 48
inventory_days: 48
receivable_days: 48
payable_days: 48
fixedasset: 48
freecashflow: 38
netmargin: 48

600519 has missing data in:
receivable_days: 21

002095 has missing data in:
inventory_days: 22

601186 has missing data in:
inventory_days: 1

600802 has missing data in:
receivable_days: 1

002083 has missing data in:
receivable_days: 1

600115 has missing data in:
receivable_days: 2
freecashflow: 1

600368 has missing data in:
receivable_days: 1

600028 has missing data in:
receivable_days: 1

000735 has missing data in:
freecashflow: 1

002315 has missing data in:
inventory_days: 5
receivable_days: 7

601318 has missing data in:
grossMargin: 48
inventory_days: 48
receivable_days: 48
payable_days: 48
fixedasset: 48
freecashflow: 37
netmargin: 48

002365 has missing data in:
receivable_days: 1

601166 has missing data in:
grossMargin: 48
inventory_days: 48
receivable_days: 48
payable_days: 48
fixedasset: 48
freecashflow: 37
netmargin: 48

600868 has missing data in:
inventory_days: 13

600743 has missing data in:
receivable_days: 3

600311 has missing data in:
grossMargin: 1
revenue: 1
inventory_days: 1
receivable_days: 3
payable_days: 1

000848 has missing data in:
receivable_days: 4

000567 has missing data in:
grossMargin: 14
inventory_days: 21
receivable_days: 35
payable_days: 20

002062 has missing data in:
receivable_days: 2

600380 has missing data in:
receivable_days: 2

601628 has missing data in:
grossMargin: 48
inventory_days: 48
receivable_days: 48
payable_days: 48
fixedasset: 48
freecashflow: 37
netmargin: 48

601688 has missing data in:
grossMargin: 48
inventory_days: 48
receivable_days: 48
payable_days: 48
fixedasset: 48
freecashflow: 36
netmargin: 48

600231 has missing data in:
receivable_days: 1

300033 has missing data in:
inventory_days: 48
payable_days: 22

600016 has missing data in:
grossMargin: 48
inventory_days: 48
receivable_days: 48
payable_days: 48
fixedasset: 48
freecashflow: 28
netmargin: 48

300021 has missing data in:
receivable_days: 1

600779 has missing data in:
receivable_days: 2

600815 has missing data in:
receivable_days: 1

600622 has missing data in:
receivable_days: 2

601601 has missing data in:
grossMargin: 48
inventory_days: 48
receivable_days: 48
payable_days: 48
fixedasset: 48
freecashflow: 26
netmargin: 48

600000 has missing data in:
grossMargin: 48
inventory_days: 48
receivable_days: 48
payable_days: 48
fixedasset: 48
freecashflow: 34
netmargin: 48

000965 has missing data in:
receivable_days: 5

000726 has missing data in:
freecashflow: 1

There are 111 stocks have missing data
29 stocks have columns that are missing completely.

The number of complete missing column:
date: 0
grossMargin: 27
revenue: 0
inventory_days: 28
receivable_days: 28
payable_days: 27
debt_ratio: 0
fixedasset: 27
freecashflow: 0
cashtoemployee: 0
netmargin: 26
num_shareholder: 0
net_equity: 0

In [16]:
for tic in tic_list[:3]:
    price_df = pd.read_csv(f"./data/590data/2010-2021_592_fq/{tic}.csv", index_col=0)
    fund_df = pd.read_csv(fund_path + tic + ".csv", index_col=0).iloc[8:]
    fund_df['tic'] = tic
    pub_d = df.loc[tic]['pubDate'].to_list()
    stat_d = df.loc[tic]['statDate'].to_list()
    trans_dict = dict(zip(stat_d, pub_d))
    fund_df.date = fund_df.date.map(trans_dict)
    
price_df.rename(columns={"Date": "date"}, inplace=True)

price_df.merge(fund_df, on="date")

,date,Open,Close,High,Low,Volume,grossMargin,revenue,inventory_days,receivable_days,payable_days,debt_ratio,fixedasset,freecashflow,cashtoemployee,netmargin,num_shareholder,net_equity,tic
0,2010-04-23,20.44,20.54,21.11,20.44,9812.39,4.9506,9.326452e+08,18.8025,36.3269,56.294050,50.3836,5.025582e+09,-8.282699e+08,6.567754e+07,3.3519,87785.0,5.404846e+09,000543
1,2010-08-24,17.82,17.86,17.98,17.40,8161.02,0.9232,7.628001e+08,21.4990,32.6477,57.422652,52.8075,5.014268e+09,-1.276295e+09,1.451534e+08,3.5228,83484.0,5.138724e+09,000543
2,2010-10-27,19.33,18.91,19.33,18.91,17711.46,0.1874,9.965623e+08,18.6303,35.1920,66.312966,54.6245,4.865571e+09,-1.397725e+09,2.184005e+08,4.0479,81990.0,5.123374e+09,000543
3,2011-03-18,18.24,18.47,18.61,18.24,13239.10,0.5659,1.092277e+09,13.9392,36.4897,52.127144,57.8041,4.923252e+09,-2.022087e+09,2.916614e+08,2.2791,78902.0,5.322664e+09,000543
4,2011-04-28,22.39,21.41,22.97,20.90,30280.62,-1.0792,9.730159e+08,14.7730,38.3142,44.424494,58.0940,4.848914e+09,-1.110184e+09,9.326512e+07,4.4916,70039.0,5.315397e+09,000543
5,2011-08-17,15.66,15.75,16.08,15.54,9664.56,-0.3129,1.047969e+09,15.7087,35.5492,41.472755,59.8437,7.844281e+09,-1.220345e+09,1.728313e+08,2.9680,60774.0,5.188093e+09,000543
6,2011-10-20,12.78,12.30,12.83,12.23,4019.26,0.7727,1.535185e+09,14.6661,37.3072,44.629699,62.0249,7.776433e+09,-1.667999e+09,2.501359e+08,0.6868,63012.0,5.073271e+09,000543
7,2012-03-23,12.41,12.04,12.44,12.02,2902.55,0.4191,1.594203e+09,15.2805,36.4306,56.157994,63.7156,7.946574e+09,-2.821300e+09,3.582876e+08,0.2755,67246.0,4.910198e+09,000543
8,2012-04-27,13.13,12.90,13.15,12.74,7939.78,9.0188,1.568837e+09,25.4806,35.1727,66.941868,66.7547,7.840040e+09,-2.155773e+09,9.865889e+07,-1.7634,66003.0,5.192649e+09,000543
9,2012-08-20,14.77,14.96,15.05,14.54,7273.54,8.4781,1.633490e+09,28.2668,39.6589,72.262518,66.4743,1.151805e+10,-6.117992e+08,1.826950e+08,-0.3606,60955.0,5.397309e+09,000543
10,2012-10-26,15.10,15.05,15.21,14.68,9243.53,10.7940,2.264306e+09,17.6082,33.6839,64.281443,68.4516,1.130643e+10,-2.757992e+08,2.738280e+08,0.5645,57735.0,5.667173e+09,000543
11,2013-04-26,15.61,15.33,15.80,15.21,7593.94,18.8614,2.040392e+09,11.0058,37.9219,71.757931,67.0248,1.121147e+10,-7.630625e+08,1.087759e+08,4.9213,60198.0,7.530689e+09,000543
12,2013-08-23,15.09,14.84,15.09,14.53,8402.52,18.1169,3.260278e+09,8.9075,32.8509,50.773120,59.3264,1.445562e+10,-1.073883e+09,2.207430e+08,7.2452,59896.0,8.349820e+09,000543
13,2013-10-31,17.67,17.18,17.67,17.01,29472.09,20.3068,3.599098e+09,NaN,29.1797,51.442627,58.6096,1.471538e+10,2.159345e+08,3.307484e+08,9.8995,57976.0,9.421911e+09,000543
14,2014-03-18,16.15,16.15,16.40,15.89,15663.63,20.0683,3.668006e+09,8.4841,33.2785,49.519265,55.8448,1.464455e+10,4.155671e+08,4.882132e+08,13.1778,56796.0,9.975620e+09,000543
15,2014-04-24,15.98,15.63,15.98,15.56,20434.80,17.5713,3.325334e+09,10.4309,35.8437,42.161639,54.3037,1.451891e+10,1.287676e+09,1.439666e+08,15.0990,58673.0,1.026043e+10,000543
16,2014-08-12,16.66,16.71,16.73,16.51,23983.17,17.9774,3.403617e+09,11.0740,34.8203,38.466576,53.2655,1.428390e+10,3.859385e+08,2.667217e+08,14.6022,61702.0,1.011580e+10,000543
17,2014-10-28,18.50,19.09,19.11,18.33,37520.67,19.4923,3.244810e+09,11.7245,31.4118,33.273372,53.7418,1.408682e+10,1.818168e+09,3.965341e+08,14.3948,56445.0,1.087200e+10,000543
18,2015-04-30,39.00,39.47,40.43,38.47,211092.74,26.8775,3.088529e+09,10.1354,36.8958,30.323059,45.5475,1.366943e+10,2.137690e+09,1.650497e+08,12.6870,55073.0,1.334721e+10,000543
19,2015-08-25,30.70,28.97,31.87,28.97,127185.41,25.7247,2.765466e+09,11.1154,34.3531,32.342752,43.2707,1.348518e+10,4.499777e+08,3.027398e+08,14.5498,55359.0,1.347540e+10,000543
20,2015-10-23,35.02,35.29,35.54,34.52,149672.24,24.0181,2.870292e+09,9.9336,31.9489,29.871860,43.0191,1.323681e+10,1.973163e+09,4.502123e+08,16.9174,51310.0,1.227898e+10,000543
21,2016-03-30,29.10,29.65,29.65,29.02,54640.81,22.9540,2.573440e+09,10.0090,37.2841,33.548461,43.0401,1.313258e+10,1.233639e+09,6.250912e+08,17.0716,91826.0,1.310077e+10,000543
22,2016-08-31,35.54,35.06,35.72,34.75,158719.38,17.4796,1.889289e+09,7.3984,42.3749,38.056528,40.1166,1.263043e+10,2.205114e+08,2.556125e+08,18.1850,81392.0,1.231771e+10,000543
23,2016-10-28,36.38,36.51,37.00,36.16,120374.26,15.3457,3.019679e+09,9.1397,39.5159,31.795145,46.2730,1.243326e+10,6.342697e+08,3.823529e+08,15.4428,74158.0,1.287874e+10,000543
24,2017-04-06,31.00,31.09,31.18,30.83,57423.40,11.7951,3.379650e+09,7.8933,42.6920,35.543043,45.6647,1.243155e+10,1.720038e+08,5.962048e+08,14.6734,70927.0,1.487858e+10,000543
25,2017-08-31,25.31,25.26,25.40,25.13,22142.72,0.1007,2.756078e+09,7.1076,39.9742,32.215860,44.6230,1.408434e+10,-6.724303e+08,2.825458e+08,5.4862,74971.0,1.405855e+10,000543
26,2017-10-31,24.46,24.46,24.51,24.38,14574.92,3.3737,3.159770e+09,5.7647,38.4824,30.400422,46.4992,1.381197e+10,-1.085775e+09,4.157309e+08,2.7918,73741.0,1.460363e+10,000543
27,2018-04-24,19.80,20.07,20.11,19.71,16267.05,5.3038,3.010116e+09,6.2382,35.6365,36.061722,48.0776,1.359341e+10,-1.113008e+09,1.614747e+08,0.6495,73788.0,1.360029e+10,000543
28,2018-10-31,18.02,18.20,18.29,17.98,16212.42,5.8397,3.666635e+09,4.5796,33.5662,38.877551,49.0205,1.522561e+10,-3.402655e+08,4.404100e+08,2.9765,67438.0,1.324600e+10,000543
29,2019-10-31,20.92,20.56,21.01,20.52,15501.59,8.7724,4.262272e+09,11.3238,33.1211,34.389598,53.8666,1.671443e+10,4.546204e+09,4.948553e+08,6.4778,59753.0,1.776540e+10,000543
30,2020-04-29,17.15,17.11,17.20,17.02,17135.50,7.5222,3.476201e+09,10.9712,39.0168,28.747570,45.5190,1.615890e+10,7.895191e+08,1.637381e+08,7.5189,61124.0,1.836237e+10,000543
31,2020-10-23,19.59,19.31,19.59,19.27,35401.17,8.5693,4.181273e+09,9.7488,39.0755,28.802164,44.3485,1.541195e+10,1.686274e+09,4.735116e+08,7.5293,56714.0,1.927676e+10,000543
32,2021-03-26,20.24,20.61,21.02,20.00,160594.02,8.7608,5.003192e+09,7.2882,35.2451,23.442286,42.7802,1.529421e+10,9.446214e+08,7.704363e+08,7.4505,61663.0,1.935297e+10,000543
33,2021-04-29,18.39,17.83,18.48,17.79,87782.31,3.0813,4.172093e+09,8.0825,34.6607,22.164164,42.5592,1.501151e+10,1.674926e+09,1.959995e+08,7.9319,66451.0,1.907846e+10,000543
34,2021-08-31,17.76,18.04,18.09,17.66,50037.49,3.2242,4.928815e+09,8.5731,35.5816,25.307353,44.4688,1.476403e+10,-3.886134e+08,3.729525e+08,7.2319,66346.0,1.913410e+10,000543
35,2021-10-29,19.92,20.68,20.91,19.92,202562.64,-1.1525,5.777599e+09,6.9287,30.5658,24.839628,47.2489,1.462630e+10,-2.741191e+08,5.787304e+08,4.1292,64584.0,1.805479e+10,000543
36,2022-04-28,17.11,16.68,17.29,16.63,61636.20,-4.5909,6.153760e+09,8.7909,29.5002,18.982123,51.1798,1.463216e+10,-2.436273e+09,8.249444e+08,-3.0445,56172.0,1.667560e+10,000543